---
- name: node
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true
  roles:
  - setup
- name: bm prereq
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: true
  roles:
  - prereq
   

